### ISSUE TITLE
Regex problem

### ISSUE THREAD

**Issue by digiwano** [GianlucaGuarini/allora#2]
```
function isTimer (fn) {
  var name = fn.name === 'valueOf' ? fn.name : fn.toString()
  return /set[Timeout|Interval|Immediate]|requestAnimationFrame|timer/.test(name)
}
```

You want `set(Timeout|Interval|Immediate)`, the above is equivalent to if you'd done: `set[ITadeilmnortuv|]`, which would for example detect `seti` as the name of a timer function. You 
should probably also use ^ and $ to terminate your regex. The two of these combined could cause, for example, a function called 'settleLedger' to match your isTimer check :)

**Comment by caseyhoward** [comment]
> should probably also use ^ and $ to terminate your regex

@digiwano I was thinking the same thing, however he calls fn.toString() and stores that into name for whatever reason so an exact string match won't work. That will give you the entire function body. So if the function happens to call one of the other functions (setTimeout, setInterval, etc) it will also match. This seems like a bug too.

**Comment by GianlucaGuarini** [comment]
I was thinking to remove the regex and just detect whether the first argument of the function is a number. I think in this way it's a bit more reliable. Thanks for your feedback guys

**Comment by caseyhoward** [comment]
@GianlucaGuarini That doesn't work for all cases. For example, setTimeout usually takes a function as its first argument. https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout

Tbh, I didn't know you could pass setTimeout just a number.
